logging:
  level:
    org:
      springframework:
        web: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/danspro
    username: root
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages.basename: i18n/messages
  application:
    name: DANSPRO TEST
server:
  port: 8080
  tomcat:
    threads:
      max: 1000
    connection-timeout: 5s
com:
  irfaan:
    danspro:
      token-key: ${TOKEN_KEY}
      token-age: ${TOKEN_AGE}
